//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuotePanel.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuotePanel.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команды, которые ты можешь отправить(допускается написание со строчной буквы)
        ///
        ///            Добавить 3(это должен быть репост записи, 3 - это квота)
        ///
        ///            Список(список постов, которые отслеживает бот)
        ///
        ///            Проверить 1(проверить квоту поста, где 1 - это id поста)
        ///
        ///            Проверить(аналогично предыдущей команде, но работает, если это репост записи, которую нужно проверить)
        ///
        ///            Закрыть 1(удаляет пост из базы бота, 1 - это id поста)
        ///
        ///            Закрыть(аналогично предыд [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заадминить http://vk.com/id11111111
        ///            или
        ///            Заадминить http://vk.com/pavel
        ///            (добавить человека в список модеров)
        ///
        ///            Разадминить http://vk.com/id11111111
        ///            или
        ///            Разадминить http://vk.com/pavel
        ///            (удалить человека из списка модеров)
        ///
        ///            Админы(выводит список модеров).
        /// </summary>
        public static string HelpAdmin {
            get {
                return ResourceManager.GetString("HelpAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет
        ///В этом посту квота проверяется автоматически)
        ///Для внесения в список комментарий следует писать так:
        ///
        ///Иванов Иван 101
        ///Иванов Иван Иванович 101
        ///
        ///По вопросам работоспособности - https://vk.com/reemind.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
    }
}
